import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className='max-h-screen min-h-screen min-w-screen max-w-screen relative overflow-hidden flex' style={{backgroundColor: 'rgba(30, 30, 100, 0.95'}}>
          {children}
        </div>
      </body>
    </html>
  )
}
