const COMMON_SETTINGS = require('../common');
export const WEBSOCKET_SESSION_SERVER_CONN_STRING = COMMON_SETTINGS.WEBSOCKET_SESSION_SERVER_CONN_STRING;
export const MessageTypes = COMMON_SETTINGS.MessageTypes;
export const MAX_STREAM_BUFFER_SIZE = 128000;

export enum ApiStatusCodes
{
    STATUS_SUCCESS = 0,
    STATUS_ERROR = -1,
    STATUS_ACCESS_DENIED = 0xC0000022,
};
